### ISSUE TITLE
No docker image for version 3.11.1

### ISSUE THREAD

**Issue by garvit-scio** [heidiks/rabbitmq-delayed-message-exchange#10]
If possible, could you please add one here https://hub.docker.com/r/heidiks/rabbitmq-delayed-message-exchange/tags

**Comment by garvit-scio** [comment]
For more contex, this is needed because upgrading from 3.10 to 3.12 complains due to the feature flag classic_queue_type_delivery_support not being enabled
```
2023-12-28 13:38:51.996095+00:00 [error] <0.230.0> Feature flags: `classic_queue_type_delivery_support`: required feature flag not enabled! It must be enabled before upgrading RabbitMQ.
2023-12-28 13:38:52.003059+00:00 [error] <0.230.0> Failed to initialize feature flags registry: {disabled_required_feature_flag,
2023-12-28 13:38:52.003059+00:00 [error] <0.230.0>                                               classic_queue_type_delivery_support}
```

This flag is only present in 3.11. So we need to upgrade to 3.11, enable the flag, and then upgrade to 3.12

**Comment by jixt** [comment]
Indeed. We need to have 3.11.x for upgrading from 3.10.x to 3.12.x. More information can be found here. https://www.rabbitmq.com/feature-flags.html#core-feature-flags.

**Comment by garvit-scio** [comment]
@heidiks sorry about the annoyance, but it would be very helpful if you could add this (I'm not sure if someone else can trigger the workflow to push the image)

**Comment by heidiks** [comment]
Hey @garvit-scio my bad, the file was created but the release was not, so [the build to push the image wasn't triggered](https://github.com/heidiks/rabbitmq-delayed-message-exchange/actions/runs/7696197594).
Can you check if it works?

**Comment by garvit-scio** [comment]
works now, thanks! 🍻

**Comment by heidiks** [comment]
@garvit-scio,

It seems to be working properly now
I had problems building on arm64 architecture and changing the image base to rabbit **3.11.28**, looks like it worked.

<img width="513" alt="image" src="https://github.com/heidiks/rabbitmq-delayed-message-exchange/assets/11573060/ee3ef7e5-62ae-422b-96d8-40b25f166ea9">


Can you check it again?

**Comment by garvit-scio** [comment]
3.11.28 works. but 3.11.1 also worked. we use x86, maybe that's why.
