### ISSUE TITLE
"v" prefix for certain versions of the plugin

### ISSUE THREAD

**Issue by Reintjuu** [heidiks/rabbitmq-delayed-message-exchange#5]
While troubleshooting a newer version (3.12.0) I found out some versions of the plugin (https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases) seem to have a "v" prefix. I noticed some of your builds are failing, but I couldn't download the build logs anymore. I don't know whether that resolves that specific issue.

**Comment by heidiks** [comment]
Hey @Reintjuu, 

These errors were fixed in the new Dockerfile.
Thanks for letting me know.
